namespace SearchNow.src.objects.notification
{
    /// <summary>
    /// Represents a notification generated by the forum application.
    /// </summary>
    public class Notification
    {
        public int NotificationId { get; set; }
        public int UserId { get; set; }

        public string Username {  get; set; }
        public string Message { get; set; }
        public DateTime Timestamp { get; set; }
        public bool IsRead { get; set; }

    }
}

